### ISSUE TITLE
What to send over the wire (kafka)?

### ISSUE THREAD

**Issue by jinder1s** [eduNEXT/openedx-events#38]
Currently, arch-bom, a team at edX, is testing MVP Kafka event bus integration into the Open edX platform. During the implementation, a couple of questions were raised and github issues seems like a great public venue to have the discussion.

Questions:
1. What is sent over the over the wire in Kafka? 
    The options are:
           a. The serialized versions of the attrs decorated classes implemented in[ data.py](https://github.com/eduNEXT/openedx-events/blob/main/openedx_events/learning/data.py)
           b. The serialized version of signal classes implemented in [signal.py](https://github.com/eduNEXT/openedx-events/blob/main/openedx_events/learning/signals.py)
           c. The serialized version of data attribute in signal classes.[ Example](https://github.com/eduNEXT/openedx-events/blob/main/openedx_events/learning/signals.py#L32-L34)
2. What is sent by a django signals sender?
    I do not know django signals very well, so I curious if the intention is for django signals to send the signals classes implemented in [signal.py](https://github.com/eduNEXT/openedx-events/blob/main/openedx_events/learning/signals.py). Or will the signal sender also send exactly the same information as a Kafka producer.
3. Depending on which option we choose above for Kafka, what happens when we need to change data definition(schema)? Specifically, which unit changes? 
    Choices:
        a. Attrs decorated classes in data.py
        b. signals class in signal.py
        c. Both??

My main goal for this discussion is pinpointing what to use to create a schema for Kafka. So far, I've been using the Attrs decorated classes in data.py.

**Comment by jinder1s** [comment]
@robrap I created this issue to further along discussions on Kafka/schema/signals from this convo: https://edx-internal.slack.com/archives/C024JPE27PV/p1642175923001100

**Comment by ormsbee** [comment]
@mariajgrimaldi and @felipemontoya are closer to this work, but I'll take a stab at this based on some early design thoughts and my understanding of where we're at. I'm also going to answer in a slightly different order because I think it makes it easier:

## In-process Signals

> 2. What is sent by a django signals sender?
>  I do not know django signals very well, so I curious if the intention is for django signals to send the signals classes implemented in [signals.py](https://github.com/eduNEXT/openedx-events/blob/main/openedx_events/learning/signals.py). Or will the signal sender also send exactly the same information as a Kafka producer.

[`OpenEdxPublicSignal`](https://github.com/eduNEXT/openedx-events/blob/807afff4d07d034608ed9aa988eed39ec0d089e4/openedx_events/tooling.py) subclasses Django's built-in `Signal` class, so we'd [send it in the same way](https://docs.djangoproject.com/en/4.0/topics/signals/#sending-signals) under the covers (well, more or less–we have [extra validation](https://github.com/eduNEXT/openedx-events/blob/807afff4d07d034608ed9aa988eed39ec0d089e4/openedx_events/tooling.py#L120-L147) that happens first).

On the receiving side, the convention used by Django signals is to send data in keyword arguments, since that allows you to add more data to the Signal in a backwards compatible way. OpenEdxPublicSignal echoes that convention and builds on top of it. So taking one example:

```python
STUDENT_REGISTRATION_COMPLETED = OpenEdxPublicSignal(
    event_type="org.openedx.learning.student.registration.completed.v1",
    data={
        "user": UserData,
    }
)
```

The contents of the `data` dict are expanded out into `**kwargs`. There's also a `metadata` keyword argument added to hold things like the event type–probably most useful when we want to send this message across the network. A receiver might look something like:

```python
@receiver(STUDENT_REGISTRATION_COMPLETED)  # note: we'd probably use manual signal connecting instead
def send_welcome_notification(sender, user, **kwargs):
    # do something here
```

Later on, when `demographics` gets added as a new data item, the above code still works.

## Kafka message format

> What is sent over the over the wire in Kafka?
> The options are:
> a. The serialized versions of the attrs decorated classes implemented in data.py
> b. The serialized version of signal classes implemented in signal.py
> c. The serialized version of data attribute in signal classes. Example

I'm not totally sure if I get your meaning, but I think my take would be (b)–or at least all the data from (b) even if we don't have access to the object itself (see example below). It would be really nice if we had a call that could convert a whole OpenEdxPublicSignal instance into a message format that goes over the wire. If it could be implemented at the receiver level, we could hook up a bunch of Signals to a handler like:

```python
def send_signal_to_kafka(sender, metadata, **kwargs):
    # furious hand-waving
    message = create_message(metadata, **kwargs)
    kafka.send(message)
```

Whether that takes the form of Avro or JSON, I don't have any strong opinions on. I would caution against picking a format for purely performance reasons though, since I'm guessing our performance bottlenecks won't be in the serialization format.

My hope is that the processes that are pulling off of Kafka on the other end will get enough data to send their own `OpenEdxPublicSignal` internally. The `metadata` would be enough to figure out which instance to call send on, and the rest of the data gets deserialized into named arguments. So as a developer writing a Django app and interested in these events, you write the same code whether you're listening for the Signal in-process or in another service.

## Evolving the format over time

> Depending on which option we choose above for Kafka, what happens when we need to change data definition(schema)? Specifically, which unit changes?
> Choices:
> a. Attrs decorated classes in data.py
> b. signals class in signal.py
> c. Both??

I'm personally in favor of adding new things as new `attrs` classes–so as new entries in an OpenEdxPublicSignal's `data` dictionary. I think that it makes clients easier to write and maintain if you only have to check whether a keyword arg was sent at all, rather than also having to worry about what version of data was sent. It's also more consistent with Django signals conventions, where data is added incrementally as new keyword args. In the example I gave with `STUDENT_REGISTRATION_COMPLETED`, it would mean that `demographics` was added as a new keyword arg in some future version, rather than adding new data into the `user` argument.

**Comment by felipemontoya** [comment]
I think this is a great place to have the discussion. Easier to follow in context than a thread in slack.

Now, I think the description that @ormsbee made about the django signals is very clear and I agree with all of it. Perhaps I'll add that all forms of connecting to the signal as a receiver are well supported and one could:
- connect the signal manually as we do [already for current events ](https://github.com/openedx/edx-platform/blob/db32ff2cdf678fa8edd12c9da76a76eef0478614/openedx/core/djangoapps/user_authn/views/tests/test_events.py#L80)`STUDENT_REGISTRATION_COMPLETED.connect(event_receiver)`
- use the decorator. `@receiver(STUDENT_REGISTRATION_COMPLETED) ...`
- use the `signals_config` [in a plugin definition](https://github.com/eduNEXT/eox-hooks/blob/master/eox_hooks/apps.py#L64)

About the Kafka question, I have been tuning in to the current discussion but I have zero experience with it. From my understanding, you would like to send both the `data` passed to the `OpenEdxPublicSignal` and the `metadata` as well. Specially since that is the part that contains everything that makes a signal compatible with OEP-41. That probably also means option b. A simple way of serializing could mean the metadata _renaming the event_type to type_ + id + data which would make the message a CloudEvents 1.0 kind of message already.

To the point of changing the data definition. We have had some [discussions about this in the past that culminated in an ADR](https://github.com/eduNEXT/openedx-events/blob/main/docs/decisions/0002-events-naming-and-versioning.rst#decisions) which I'm very much in favor of keeping. In summary Signals conform to semver2, so changes immediately triggers a major or minor change depending on the backwards compatibility of the change.
Should the change be major, then a complete new signal with a new definition would be required. On the "Consequences" section of the ADR, we made a note about new signals requiring that both are maintained for a while and follow a deprecation process.
```python
STUDENT_REGISTRATION_COMPLETED = OpenEdxPublicSignal(
    event_type="org.openedx.learning.student.registration.completed.v1",
    data={
        "user": UserData,
    }
)
STUDENT_REGISTRATION_COMPLETED_V2 = OpenEdxPublicSignal(
    event_type="org.openedx.learning.student.registration.completed.v2",
    data={
        "registration": RegistrationData,
    }
)
```

In case the change is minor, then we only add entries to the `data` dict of the signal and add a `minor_version` to the definition.
```python
STUDENT_REGISTRATION_COMPLETED = OpenEdxPublicSignal(
    event_type="org.openedx.learning.student.registration.completed.v1",
    minor_version=1,
    data={
        "user": UserData,
        "form": RegistrationFormData,
    }
)
```

**Comment by robrap** [comment]
Thanks for all your thoughts.

1. Regarding Kafka consumers, most example code ensure messages are processed by combining the listening, processing, error handling, and acknowledging (i.e. moving on). It would be a very different pattern to just send a signal and assume everything is doing what it needs to. This probably warrants a longer discussion that maybe should be its own thread?

2. I'm trying to reconcile the way explicit schemas, and a schema registry, and schema evolution rules work with the currently proposed design that is set up to work with signals, where no explicit schema and few rules have been defined.

* Are there any rules for how and if one of the data objects might change internally, or is that left up in the air? For our explicit schema definitions, this would be much more well defined. Is that ok?
* I think we'll just need to research how and if we could translate your top-level list of optional data keys to a formal schema definition that can evolve by adding new keys. @jinder1s: Is this simple? Can you evolve a schema adding optional fields representing objects? Would it just default to null (None)?

3. Other related event design questions.
* I assume all of the top-level objects in the dict are limited to Data objects? 
* Existing example events seem to represent objects that seem agnostic to the type of event. For example, enrollment created, enrollment changed, and unenrollment completed, all just contain `CourseEnrollmentData`. What if there were data specific to creation or update or completion? Would we add a `CourseEnrollmentUpdatedData` class, as an example, to handle one additional field? Or, would we start adding fields to `CourseEnrollmentData` that only make sense for a subset of the events? This may not be important at this time. I'm not sure, but I'm trying to map a single schema per event to the dict of reusable data classes. Additionally, I have read it recommended not to try to reuse data definitions across events, and I'm trying to understand if that was a bad or good recommendation. Note: we have not started differentiating these events (other than via `event_type`), and we haven't started evolving our events (for any reason), so it may be too early to judge.

**Comment by ormsbee** [comment]
> 1. Regarding Kafka consumers, most example code ensure messages are processed by combining the listening, processing, error handling, and acknowledging (i.e. moving on). It would be a very different pattern to just send a signal and assume everything is doing what it needs to. This probably warrants a longer discussion that maybe should be its own thread?

A consumer still has that option. Django signals look asynchronous, but they're really just synchronously dispatching in-process. The `send_event` method even has a `send_robust` flag already, so we can stop processing at the first handler that goes wrong. Whatever is listening to the Kafka queue as a consumer could do something like:

```python
def message_handler(message):
    signal, data = create_signal_from_message(message)  # Do the lookup based on event_id and fill in the fields.
    results = signal.send_event(**data)
    # At this point in the code, all handlers have executed. We can inspect results, catch errors, etc.
    kafka.ack_msg()  # (waves hands)
```

> 2. I'm trying to reconcile the way explicit schemas, and a schema registry, and schema evolution rules work with the currently proposed design that is set up to work with signals, where no explicit schema and few rules have been defined.

I don't know the specifics of schema specification. I had thought that it would be possible to generate the schema from the `attrs` data classes, either dynamically at runtime, or via code generation.

Would it help if you fleshed out how we'd want to do schema specification if signals were completely out of the picture, and then we can see what it would take to bridge the two?

> * Are there any rules for how and if one of the data objects might change internally, or is that left up in the air?

I'd say that the data objects shouldn't change internally, and that all new data should be new objects.

> For our explicit schema definitions, this would be much more well defined. Is that ok?

Probably? What would we express in the schema definition that we couldn't derive from the signal definition and attrs classes?

> * I think we'll just need to research how and if we could translate your top-level list of optional data keys to a formal schema definition that can evolve by adding new keys. @jinder1s: Is this simple? Can you evolve a schema adding optional fields representing objects? Would it just default to null (None)?

Based on my brief reading of [Avro compatibility modes](https://docs.confluent.io/platform/current/schema-registry/avro.html), I think we'd be shooting for `FORWARD` or `FORWARD_TRANSITIVE` compatibility. The producer gets upgraded first, and the consumers can lag behind a bit–which seems appropriate for our situation since something like `COURSE_ENROLLMENT_CREATED` may have a whole bunch of consumers that may or may not be updated in a timely fashion. That allows for the addition of new fields as the schema evolves, with old consumers just ignoring the new stuff they don't understand.

> 3. Other related event design questions.
>
> I assume all of the top-level objects in the dict are limited to Data objects?

I don't think they have to be. There are some use cases where I could see a single top-level primitive being added, like a boolean for `has_pii` or a string for `site` for people running multiple instances. It's also possible that there will be just one tiny extra piece of data that folks want to include in a message, but can't add it to an existing attrs data class because of the "don't change it, make a new entry" rule that I'd like to see us use. 

> Existing example events seem to represent objects that seem agnostic to the type of event. For example, enrollment created, enrollment changed, and unenrollment completed, all just contain CourseEnrollmentData. What if there were data specific to creation or update or completion? Would we add a CourseEnrollmentUpdatedData class, as an example, to handle one additional field? Or, would we start adding fields to CourseEnrollmentData that only make sense for a subset of the events? This may not be important at this time. I'm not sure, but I'm trying to map a single schema per event to the dict of reusable data classes. Additionally, I have read it recommended not to try to reuse data definitions across events, and I'm trying to understand if that was a bad or good recommendation. Note: we have not started differentiating these events (other than via event_type), and we haven't started evolving our events (for any reason), so it may be too early to judge.

I'm in favor of adding new top-level objects/primitives, and not adding fields to existing classes. It looks uglier, but it's more predictable.

**Comment by robrap** [comment]
Thanks @ormsbee for your thoughtful responses.

>> 1. Regarding Kafka consumers, ...

> A consumer still has that option. Django signals look asynchronous, ...

Yes. It seems there are options here. We will be working on this shortly, so we'll understand more soon.

>> 2.  I'm trying to reconcile the way explicit schemas, and a schema registry, and schema evolution rules work with the currently proposed design...

> I don't know the specifics of schema specification. I had thought that it would be possible to generate the schema from the attrs data classes, either dynamically at runtime, or via code generation.

Yes. This is what we was implemented for runtime generation here: https://github.com/eduNEXT/openedx-events/blob/main/openedx_events/avro_attrs_bridge.py. This code assumes that attrs with a default represents an optional field.

However, after Jinder built that code that can convert a Data attrs class, we learned more about the top-level data dict in the Signal class, which led to this discussion. Because this top-level data dict is not using attrs, we don't have defaults to determine what should be optional. I guess we'd assume that every top-level dict field is required, which would force `FORWARD` compatibility at best, to enable adding fields.

Based on recommendations we had read, I was hoping for "FULL" compatibility and loosening as needed. I guess that is still possible, as long as the top-level doesn't change. Note: the idea of a consumer (separate squad) being able to flexibly deploy an update that is ready for new events as soon as they are produced, seems nice.

>> * Are there any rules for how and if one of the data objects might change internally, or is that left up in the air?

> I'd say that the data objects shouldn't change internally, and that all new data should be new objects.

Interesting. I imagined that you were thinking something looser than I was thinking, but instead, it seems you were thinking something more strict. Note that `FULL` compatibility is an option where optional fields could be added or removed.

>> * For our explicit schema definitions, this would be much more well defined. Is that ok?

> Probably? What would we express in the schema definition that we couldn't derive from the signal definition and attrs classes?

I guess "more well defined" should have been "more explicit", because of the schema registry and schema evolution checks. I can confirm that the attrs classes can convert to a schema definition. As noted above, the data dict will be able to as well, but will be less flexible because attrs have default capabilities and a dict does not (unless we add a custom mechanism for this).

>> 3.  Other related event design questions.
>> * I assume all of the top-level objects in the dict are limited to Data objects?

> I don't think they have to be. There are some use cases where I could see a single top-level primitive being added,...
> I'm in favor of adding new top-level objects/primitives, and not adding fields to existing classes. It looks uglier, but it's more predictable.

Ah. Glad I'm checking my invalid assumptions. I'm also glad for the flexibility. I still don't love the exceptional nature of the top-level dict, relative to all the attrs classes, but oh well. Again, it is possible that allowing the addition of optional fields into existing Data classes might keep some changes cleaner, but I guess that is a future event design option that we haven't yet made impossible.

**Comment by ormsbee** [comment]
@robrap: Thanks for the quick reply. I think I have a better understanding of where you folks are coming from now.

>  I guess we'd assume that every top-level dict field is required, which would force FORWARD compatibility at best, to enable adding fields.

Yeah, I guess I'd lean towards having all top-level dict fields be required.

Okay, so my understanding of how Avro serialization works is rudimentary at best, so please bear with me if this is a really silly question: *Do we need optional fields in the schema at all?*

It's true that we have defaults in our data structures, but those values are being filled in as soon as the data class is instantiated. The values are never going to be _missing_ when it gets to the stage of serializing to send over Kafka. So for the purposes of the Avro schema, can we specify them as required fields that will always be present, but sometimes the value will be null?

Regardless, we should probably make the type information more accurate by taking into account the whole nullable-field thing in our attrs class definitions. So something like:

```python
created_by = attr.ib(type=Optional[UserData], default=None)  # instead of just type=UserData
```

**Comment by robrap** [comment]
@ormsbee: Just a quick response to:

> _Do we need optional fields in the schema at all?_

In terms of schema evolution, optional fields are needed for `FULL` compatibility (repeat of [Avro schema evolution link](https://docs.confluent.io/platform/current/schema-registry/avro.html)).

I think the benefit is that the producer and all consumers (presumably managed by a mix of owners) can deploy to the new version of the event in any order. Without optional fields, we would commit to `FORWARD` compatibility, and consumers could not deploy code for a newer event until it is already being produced. I can imagine scenarios where that adds some friction, but all scenarios are imaginary at this point.

So, it is possible for us to say we won't support optional fields, or that we _might_ support them in the future. Note that since defaults and optional are different things, I agree that we should be more explicit _if and when_ we want to support optional fields.

**Comment by jinder1s** [comment]
Thank you all for your responses. I plan on writing an ADR based on these responses. For now I will close this issue and then ping you folks when the ADR is ready.

**Comment by jinder1s** [comment]
Hi all, I wrote three ADRs based on conversations in this issue and #39:
- 0004-event-bus-as-extension-of-django-signals.rst
- 0005-event-bus-support-forward-schema-evolution.rst
- 0006-schema-implementation-decisions.rst

To learn more about what I wrote and to review: please see PR #40. Thank You!

**Comment by robrap** [comment]
I plan on working with Jinder to get some updates to the ADRs. You all are welcome to review in their current state, but I can also let you know when our team has completed reviews/updates.
